### ISSUE TITLE
How to interpret the visualization

### ISSUE THREAD

**Issue by chengyineng38** [kayoyin/interpret-lm#2]
Hi Kayo, 

How do I interpret the visualization? I'm using the erasure method here. What does it tell me if I removed the token `stop` ? Appreciate your help and really interesting research! 

<img width="1225" alt="Screenshot 2023-04-11 at 4 22 45 PM" src="https://user-images.githubusercontent.com/59850826/231309369-5845484b-b1b4-44f0-b246-b7597b554a25.png">

**Comment by kayoyin** [comment]
Hi! The scores measure how much each token makes the model attribute higher probability to the target (instead of the foil). So in the example you gave, input tokens like `stop` makes the model to more likely predict `barking`, whereas tokens like `the` does not really influence whether the model predicts `barking` instead of `following`. Hope this helps!
