### ISSUE TITLE
Gradient x Input Embedding Approximation

### ISSUE THREAD

**Issue by MM-IR** [kayoyin/interpret-lm#3]
Hi, thanks for this amazing work!

I have the following questions:
- How to interpret the negative value w.r.t. each token here? Do we have to pick the absolute value to pick highest influential token?

**Comment by kayoyin** [comment]
Hello! Thanks for the kind words!

Input x gradient and erasure methods may give negative saliency values. In this case, what this means is that the input token makes the target _less_ likely and/or the foil _more_ likely. So to explain why the model predicts "target" instead of "foil", you should look at the highest saliency scores without taking the absolute value. If you're interested in what input token affects model output the most, whether it is making the target more or less likely, then you can take the absolute value.

I hope this helps!

**Comment by MM-IR** [comment]
Thank you for the explanations! I really appreciate it!
